In [2]:
import pandas as pd

df = pd.read_excel("dataset_final_new_new.xlsx")
df.columns = df.columns.astype(str).str.strip().str.lower()


df["year"] = pd.to_numeric(df["year"], errors="coerce")
df["sum"]  = pd.to_numeric(df["sum"], errors="coerce")


df_p = df[df["year"].between(2011, 2015)].copy()


yearly = (
    df_p.groupby(["brand", "model", "year"], as_index=False)["sum"]
    .sum()
)


ok_models = (
    yearly[yearly["sum"] > 0]
    .groupby(["brand", "model"])["year"]
    .nunique()
    .reset_index(name="n_years")
)

ok_models = ok_models[ok_models["n_years"] == 5][["brand", "model"]]


final_df = df.merge(ok_models, on=["brand", "model"], how="inner")
final_df = final_df[final_df["year"].between(2011, 2015)]

print("Моделей прошло фильтр (2011–2015):", ok_models.shape[0])
final_df.head()

Моделей прошло фильтр (2011–2015): 147

    year month  sum  brand                  model fuel    cc
12  2011   jan    0  HONDA  All New City i VTEC S    g  1497
13  2011   feb   27  HONDA  All New City i VTEC S    g  1497
14  2011   mar   31  HONDA  All New City i VTEC S    g  1497
15  2011   apr    2  HONDA  All New City i VTEC S    g  1497
16  2011   may    0  HONDA  All New City i VTEC S    g  1497

In [3]:
cc_check = (
    final_df.groupby(["brand", "model"])["cc"]
    .nunique()
    .reset_index(name="n_cc")
)


cc_problem = cc_check[cc_check["n_cc"] > 1]

print("Моделей с несколькими cc:", cc_problem.shape[0])
cc_problem.head()

Моделей с несколькими cc: 49

        brand              model  n_cc
3         BMW             740 Li     3
5         BMW  X 1 s Drive 1.8 i     2
9   CHEVROLET    Captiva 2.0 Dsl     2
11  CHEVROLET     Captiva 2.4 AT     2
17   DAIHATSU        Gran Max HI     2

In [4]:
df["cc"] = pd.to_numeric(df["cc"], errors="coerce")
df["model_cc"] = df["model"] + " " + df["cc"].astype(int).astype(str) + "cc"

df_p = df[df["year"].between(2011, 2015)].copy()

yearly = (
    df_p.groupby(["brand", "model_cc", "year"], as_index=False)["sum"]
    .sum()
)

ok_models = (
    yearly[yearly["sum"] > 0]
    .groupby(["brand", "model_cc"])["year"]
    .nunique()
    .reset_index(name="n_years")
)

ok_models = ok_models[ok_models["n_years"] == 5][["brand", "model_cc"]]

final_df = df_p.merge(ok_models, on=["brand", "model_cc"], how="inner")

print("Количество версий моделей:", ok_models.shape[0])
final_df.head()

Количество версий моделей: 122

,year,month,sum,brand,model,fuel,cc,model_cc
0,2011,jan,0,HONDA,All New City i VTEC S,g,1497,All New City i VTEC S 1497cc
1,2011,feb,27,HONDA,All New City i VTEC S,g,1497,All New City i VTEC S 1497cc
2,2011,mar,31,HONDA,All New City i VTEC S,g,1497,All New City i VTEC S 1497cc
3,2011,apr,2,HONDA,All New City i VTEC S,g,1497,All New City i VTEC S 1497cc
4,2011,may,0,HONDA,All New City i VTEC S,g,1497,All New City i VTEC S 1497cc

In [5]:
final_df.to_csv(
    "new_dataset_2011_2015_model_split_by_cc.csv",
    index=False,
    encoding="utf-8-sig"
)

In [6]:
brands_passed = ok_models["brand"].drop_duplicates().sort_values().reset_index(drop=True)

print("Количество брендов:", brands_passed.shape[0])
brands_passed

Количество брендов: 19

0               BMW
1         CHEVROLET
2          DAIHATSU
3             DODGE
4             GEELY
5              HINO
6             HONDA
7           HYUNDAI
8             ISUZU
9               KIA
10              MAN
11            MAZDA
12    MERCEDES-BENZ
13             MINI
14       MITSUBISHI
15          PEUGEOT
16           PROTON
17           TOYOTA
18       VOLKSWAGEN
Name: brand, dtype: object

In [7]:
models_le_1200 = (
    final_df[final_df["cc"] <= 1200]
    [["brand", "model_cc"]]
    .drop_duplicates()
)

print("Количество моделей с cc ≤ 1200:",
      models_le_1200.shape[0])

Количество моделей с cc ≤ 1200: 1

In [7]:
brands_passed = ok_models["brand"].drop_duplicates().sort_values().reset_index(drop=True)

print("Количество брендов:", brands_passed.shape[0])
brands_passed

Количество брендов: 23

0               BMW
1         CHEVROLET
2          DAIHATSU
3             DODGE
4             GEELY
5              HINO
6             HONDA
7           HYUNDAI
8             ISUZU
9               KIA
10       LAND-ROVER
11            LEXUS
12              MAN
13            MAZDA
14    MERCEDES-BENZ
15             MINI
16       MITSUBISHI
17           NISSAN
18          PEUGEOT
19           PROTON
20           SUZUKI
21           TOYOTA
22       VOLKSWAGEN
Name: brand, dtype: object

In [8]:

final_df = final_df.sort_values(["brand", "model", "year", "month"])


final_df.to_csv(
    "filtered_models_2011_2015.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Файл сохранён как filtered_models_2011_2015.csv")

Файл сохранён как filtered_models_2011_2015.csv

In [9]:
import pandas as pd

df = pd.read_excel("dataset_final_new_new.xlsx")
df.columns = df.columns.astype(str).str.strip().str.lower()  # на всякий


df["year"] = pd.to_numeric(df["year"], errors="coerce")
df["sum"]  = pd.to_numeric(df["sum"], errors="coerce")


df_p = df[df["year"].between(2011, 2015)].copy()


yearly = (
    df_p.groupby(["brand", "model", "year"], as_index=False)["sum"]
    .sum()
)


ok_models = (
    yearly[yearly["sum"] > 0]
    .groupby(["brand", "model"])["year"]
    .nunique()
    .reset_index(name="n_years")
)

ok_models = ok_models[ok_models["n_years"] == 5][["brand", "model"]]


final_df = df.merge(ok_models, on=["brand", "model"], how="inner")

print("Моделей прошло фильтр:", ok_models.shape[0])
final_df.head()

Моделей прошло фильтр: 147

   year month  sum  brand                  model fuel    cc
0  2010   jan   35  HONDA  All New City i VTEC S    g  1497
1  2010   feb   40  HONDA  All New City i VTEC S    g  1497
2  2010   mar   44  HONDA  All New City i VTEC S    g  1497
3  2010   apr   25  HONDA  All New City i VTEC S    g  1497
4  2010   may   36  HONDA  All New City i VTEC S    g  1497

In [10]:

final_sorted = final_df.sort_values(["brand", "model", "year", "month"])


final_sorted.to_csv(
    "ok_models_full_2011_2015.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Файл сохранён как ok_models_full_2011_2015.csv")

Файл сохранён как ok_models_full_2011_2015.csv

In [13]:

df["cc"] = pd.to_numeric(df["cc"], errors="coerce")



final_df = df.merge(ok_models, on=["brand", "model"], how="inner")


final_df = final_df[final_df["cc"] <= 1200]

print("Моделей после доп. фильтра cc < 1200:",
      final_df[["brand", "model"]].drop_duplicates().shape[0])

final_df.head()

Моделей после доп. фильтра cc < 1200: 2

      year month  sum brand        model fuel    cc
4608  2010   jan  288   KIA  Picanto OPT    g  1100
4609  2010   feb  297   KIA  Picanto OPT    g  1100
4610  2010   mar  355   KIA  Picanto OPT    g  1100
4611  2010   apr  380   KIA  Picanto OPT    g  1100
4612  2010   may  396   KIA  Picanto OPT    g  1100

In [14]:

df["cc"] = pd.to_numeric(df["cc"], errors="coerce")


final_df = df.merge(ok_models, on=["brand", "model"], how="inner")

final_df = final_df[final_df["year"].between(2011, 2015)]


final_df = final_df[(final_df["cc"] <= 1200) & (final_df["cc"] > 0)]

print("Моделей после фильтра cc ≤ 1200:",
      final_df[["brand", "model"]].drop_duplicates().shape[0])


final_df = final_df.sort_values(["brand", "model", "year", "month"])


final_df.to_csv(
    "filtered_2011_2015_cc_le_1200.csv",
    index=False,
    encoding="utf-8-sig"
)

print("CSV файл сохранён как filtered_2011_2015_cc_le_1200.csv")

Моделей после фильтра cc ≤ 1200: 2
CSV файл сохранён как filtered_2011_2015_cc_le_1200.csv

In [15]:
cc_by_model = (
    final_df.groupby(["brand", "model"])["cc"]
    .min()
    .reset_index()
)

models_cc_le_1200 = cc_by_model[cc_by_model["cc"] <= 1200]

print("Количество моделей с cc ≤ 1200:",
      models_cc_le_1200.shape[0])

models_cc_le_1200.head()

Количество моделей с cc ≤ 1200: 2

      brand                model    cc
0  DAIHATSU  All New Xenia 1.0 D   989
1       KIA          Picanto OPT  1100