In [1]:
import pandas as pd

df = pd.read_excel("dataset_final_new_new.xlsx")
df.columns = df.columns.astype(str).str.strip().str.lower()  # на всякий

df["year"] = pd.to_numeric(df["year"], errors="coerce")
df["sum"]  = pd.to_numeric(df["sum"], errors="coerce")


df_p = df[df["year"].between(2016, 2020)].copy()


    df_p.groupby(["brand", "model", "year"], as_index=False)["sum"]
    .sum()
)


ok_models = (
    yearly[yearly["sum"] > 0]
    .groupby(["brand", "model"])["year"]
    .nunique()
    .reset_index(name="n_years")
)

ok_models = ok_models[ok_models["n_years"] == 5][["brand", "model"]]


final_df = df.merge(ok_models, on=["brand", "model"], how="inner")

print("Моделей прошло фильтр:", ok_models.shape[0])
final_df.head()

Моделей прошло фильтр: 162

   year month  sum  brand                     model fuel    cc
0  2010   jan   98  HONDA  All New City i VTEC E AT    g  1497
1  2010   feb  131  HONDA  All New City i VTEC E AT    g  1497
2  2010   mar  109  HONDA  All New City i VTEC E AT    g  1497
3  2010   apr  139  HONDA  All New City i VTEC E AT    g  1497
4  2010   may   94  HONDA  All New City i VTEC E AT    g  1497

In [2]:

ok_models.reset_index(drop=True)

          brand               model
0          AUDI    Q 3 1.4 TFSI A/T
1          AUDI     Q 5 2.0 TFSI AT
2          AUDI     Q 7 3.0 TFSI AT
3           BMW               330 i
4      DAIHATSU         Gran Max BV
..          ...                 ...
157      TOYOTA           Vios E AT
158      TOYOTA              Vios G
159      TOYOTA           Vios G AT
160   UD-TRUCKS         CKE 25042 R
161  VOLKSWAGEN  Polo 1.2 GT TSI AT

[162 rows x 2 columns]

In [3]:
ok_models.to_csv("ok_models_list.csv", index=False, encoding="utf-8-sig")
print("Сохранено в ok_models_list.csv")

Сохранено в ok_models_list.csv

In [4]:

final_sorted = final_df.sort_values(["brand", "model", "year", "month"])

final_sorted.head(50)

       year month  sum brand             model fuel    cc
16323  2010   apr    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16515  2010   apr    0  AUDI  Q 3 1.4 TFSI A/T    g  3500
16327  2010   aug    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16519  2010   aug    0  AUDI  Q 3 1.4 TFSI A/T    g  3500
16331  2010   dec    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16523  2010   dec    0  AUDI  Q 3 1.4 TFSI A/T    g  3500
16321  2010   feb    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16513  2010   feb    0  AUDI  Q 3 1.4 TFSI A/T    g  3500
16320  2010   jan    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16512  2010   jan    0  AUDI  Q 3 1.4 TFSI A/T    g  3500
16326  2010   jul    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16518  2010   jul    0  AUDI  Q 3 1.4 TFSI A/T    g  3500
16325  2010   jun    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16517  2010   jun    0  AUDI  Q 3 1.4 TFSI A/T    g  3500
16322  2010   mar    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16514  2010   mar    0  AUDI  Q 3 1.4 TFSI A/T    g  3500
16324  2010   may    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16516  2010   may    0  AUDI  Q 3 1.4 TFSI A/T    g  3500
16330  2010   nov    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16522  2010   nov    0  AUDI  Q 3 1.4 TFSI A/T    g  3500
16329  2010   oct    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16521  2010   oct    0  AUDI  Q 3 1.4 TFSI A/T    g  3500
16328  2010   sep    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16520  2010   sep    0  AUDI  Q 3 1.4 TFSI A/T    g  3500
16335  2011   apr    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16527  2011   apr    0  AUDI  Q 3 1.4 TFSI A/T    g  3500
16339  2011   aug    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16531  2011   aug    0  AUDI  Q 3 1.4 TFSI A/T    g  3500
16343  2011   dec    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16535  2011   dec    0  AUDI  Q 3 1.4 TFSI A/T    g  3500
16333  2011   feb    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16525  2011   feb    0  AUDI  Q 3 1.4 TFSI A/T    g  3500
16332  2011   jan    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16524  2011   jan    0  AUDI  Q 3 1.4 TFSI A/T    g  3500
16338  2011   jul    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16530  2011   jul    0  AUDI  Q 3 1.4 TFSI A/T    g  3500
16337  2011   jun    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16529  2011   jun    0  AUDI  Q 3 1.4 TFSI A/T    g  3500
16334  2011   mar    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16526  2011   mar    0  AUDI  Q 3 1.4 TFSI A/T    g  3500
16336  2011   may    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16528  2011   may    0  AUDI  Q 3 1.4 TFSI A/T    g  3500
16342  2011   nov    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16534  2011   nov    0  AUDI  Q 3 1.4 TFSI A/T    g  3500
16341  2011   oct    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16533  2011   oct    0  AUDI  Q 3 1.4 TFSI A/T    g  3500
16340  2011   sep    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16532  2011   sep    0  AUDI  Q 3 1.4 TFSI A/T    g  3500
16347  2012   apr    0  AUDI  Q 3 1.4 TFSI A/T    g  1400
16539  2012   apr    0  AUDI  Q 3 1.4 TFSI A/T    g  3500

In [5]:

final_sorted = final_df.sort_values(["brand", "model", "year", "month"])


final_sorted.to_csv(
    "ok_models_full_2016_2020.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Файл сохранён как ok_models_full_2016_2020.csv")

Файл сохранён как ok_models_full_2016_2020.csv

In [6]:
brands_passed = ok_models["brand"].drop_duplicates().sort_values().reset_index(drop=True)

print("Количество брендов:", brands_passed.shape[0])
brands_passed

Количество брендов: 17

0                AUDI
1                 BMW
2            DAIHATSU
3                HINO
4               HONDA
5               ISUZU
6               LEXUS
7                 MAN
8          MITSUBISHI
9     MITSUBISHI-FUSO
10             NISSAN
11             SCANIA
12             SUZUKI
13               TATA
14             TOYOTA
15          UD-TRUCKS
16         VOLKSWAGEN
Name: brand, dtype: object

In [8]:

df_ok = final_df.copy()


df_daihatsu = df_ok[df_ok["brand"] == "DAIHATSU"]


df_daihatsu = df_daihatsu[["year", "month", "sum", "brand", "model"]]


df_daihatsu = df_daihatsu.sort_values(["model", "year", "month"])

df_daihatsu.head(50)

      year month  sum     brand        model
1155  2010   apr  249  DAIHATSU  Gran Max BV
1159  2010   aug  112  DAIHATSU  Gran Max BV
1163  2010   dec  230  DAIHATSU  Gran Max BV
1153  2010   feb  175  DAIHATSU  Gran Max BV
1152  2010   jan  192  DAIHATSU  Gran Max BV
1158  2010   jul  237  DAIHATSU  Gran Max BV
1157  2010   jun  313  DAIHATSU  Gran Max BV
1154  2010   mar  233  DAIHATSU  Gran Max BV
1156  2010   may  320  DAIHATSU  Gran Max BV
1162  2010   nov  509  DAIHATSU  Gran Max BV
1161  2010   oct  161  DAIHATSU  Gran Max BV
1160  2010   sep   49  DAIHATSU  Gran Max BV
1167  2011   apr  193  DAIHATSU  Gran Max BV
1171  2011   aug  244  DAIHATSU  Gran Max BV
1175  2011   dec  375  DAIHATSU  Gran Max BV
1165  2011   feb  229  DAIHATSU  Gran Max BV
1164  2011   jan  373  DAIHATSU  Gran Max BV
1170  2011   jul  573  DAIHATSU  Gran Max BV
1169  2011   jun  250  DAIHATSU  Gran Max BV
1166  2011   mar  321  DAIHATSU  Gran Max BV
1168  2011   may  262  DAIHATSU  Gran Max BV
1174  2011   nov  403  DAIHATSU  Gran Max BV
1173  2011   oct  292  DAIHATSU  Gran Max BV
1172  2011   sep  368  DAIHATSU  Gran Max BV
1179  2012   apr  372  DAIHATSU  Gran Max BV
1183  2012   aug  343  DAIHATSU  Gran Max BV
1187  2012   dec  416  DAIHATSU  Gran Max BV
1177  2012   feb  311  DAIHATSU  Gran Max BV
1176  2012   jan  400  DAIHATSU  Gran Max BV
1182  2012   jul  557  DAIHATSU  Gran Max BV
1181  2012   jun  443  DAIHATSU  Gran Max BV
1178  2012   mar  405  DAIHATSU  Gran Max BV
1180  2012   may  517  DAIHATSU  Gran Max BV
1186  2012   nov  825  DAIHATSU  Gran Max BV
1185  2012   oct  639  DAIHATSU  Gran Max BV
1184  2012   sep  421  DAIHATSU  Gran Max BV
1191  2013   apr  535  DAIHATSU  Gran Max BV
1195  2013   aug  529  DAIHATSU  Gran Max BV
1199  2013   dec  413  DAIHATSU  Gran Max BV
1189  2013   feb  310  DAIHATSU  Gran Max BV
1188  2013   jan  311  DAIHATSU  Gran Max BV
1194  2013   jul  570  DAIHATSU  Gran Max BV
1193  2013   jun  605  DAIHATSU  Gran Max BV
1190  2013   mar  392  DAIHATSU  Gran Max BV
1192  2013   may  752  DAIHATSU  Gran Max BV
1198  2013   nov  450  DAIHATSU  Gran Max BV
1197  2013   oct  487  DAIHATSU  Gran Max BV
1196  2013   sep  537  DAIHATSU  Gran Max BV
1203  2014   apr  470  DAIHATSU  Gran Max BV
1207  2014   aug  488  DAIHATSU  Gran Max BV

In [9]:
df_daihatsu.to_csv(
    "daihatsu_ok_models.csv",
    index=False,
    encoding="utf-8-sig"
)

In [10]:

df_ok = final_df.copy()


df_bmw = df_ok[df_ok["brand"].str.upper() == "BMW"]


df_bmw = df_bmw[["year", "month", "sum", "brand", "model"]]


df_bmw = df_bmw.sort_values(["model", "year", "month"])

df_bmw.head(50)

       year month  sum brand  model
18435  2010   apr    0   BMW  330 i
18627  2010   apr    0   BMW  330 i
18439  2010   aug    0   BMW  330 i
18631  2010   aug    0   BMW  330 i
18443  2010   dec    0   BMW  330 i
18635  2010   dec    0   BMW  330 i
18433  2010   feb    0   BMW  330 i
18625  2010   feb    0   BMW  330 i
18432  2010   jan    0   BMW  330 i
18624  2010   jan    0   BMW  330 i
18438  2010   jul    0   BMW  330 i
18630  2010   jul    0   BMW  330 i
18437  2010   jun    0   BMW  330 i
18629  2010   jun    0   BMW  330 i
18434  2010   mar    0   BMW  330 i
18626  2010   mar    0   BMW  330 i
18436  2010   may    0   BMW  330 i
18628  2010   may    0   BMW  330 i
18442  2010   nov    0   BMW  330 i
18634  2010   nov    0   BMW  330 i
18441  2010   oct    0   BMW  330 i
18633  2010   oct    0   BMW  330 i
18440  2010   sep    0   BMW  330 i
18632  2010   sep    0   BMW  330 i
18447  2011   apr    0   BMW  330 i
18639  2011   apr    0   BMW  330 i
18451  2011   aug    0   BMW  330 i
18643  2011   aug    0   BMW  330 i
18455  2011   dec    0   BMW  330 i
18647  2011   dec    0   BMW  330 i
18445  2011   feb    0   BMW  330 i
18637  2011   feb    0   BMW  330 i
18444  2011   jan    0   BMW  330 i
18636  2011   jan    0   BMW  330 i
18450  2011   jul    0   BMW  330 i
18642  2011   jul    0   BMW  330 i
18449  2011   jun    0   BMW  330 i
18641  2011   jun    0   BMW  330 i
18446  2011   mar    0   BMW  330 i
18638  2011   mar    0   BMW  330 i
18448  2011   may    0   BMW  330 i
18640  2011   may    0   BMW  330 i
18454  2011   nov    0   BMW  330 i
18646  2011   nov    0   BMW  330 i
18453  2011   oct    0   BMW  330 i
18645  2011   oct    0   BMW  330 i
18452  2011   sep    0   BMW  330 i
18644  2011   sep    0   BMW  330 i
18459  2012   apr    0   BMW  330 i
18651  2012   apr    0   BMW  330 i

In [11]:
df_bmw.to_csv(
    "bmw_ok_models.csv",
    index=False,
    encoding="utf-8-sig"
)

In [12]:

df_ok = final_df.copy()


df_isuzu = df_ok[df_ok["brand"].str.upper() == "ISUZU"]


df_isuzu = df_isuzu[["year", "month", "sum", "brand", "model"]]


df_isuzu = df_isuzu.sort_values(["model", "year", "month"])

df_isuzu.head(50)

      year month  sum  brand     model
5763  2010   apr    0  ISUZU  D-MAX SC
5955  2010   apr    0  ISUZU  D-MAX SC
5767  2010   aug    0  ISUZU  D-MAX SC
5959  2010   aug    0  ISUZU  D-MAX SC
5771  2010   dec    0  ISUZU  D-MAX SC
5963  2010   dec    0  ISUZU  D-MAX SC
5761  2010   feb    3  ISUZU  D-MAX SC
5953  2010   feb    0  ISUZU  D-MAX SC
5760  2010   jan   18  ISUZU  D-MAX SC
5952  2010   jan    0  ISUZU  D-MAX SC
5766  2010   jul    0  ISUZU  D-MAX SC
5958  2010   jul    0  ISUZU  D-MAX SC
5765  2010   jun    2  ISUZU  D-MAX SC
5957  2010   jun    0  ISUZU  D-MAX SC
5762  2010   mar   27  ISUZU  D-MAX SC
5954  2010   mar    0  ISUZU  D-MAX SC
5764  2010   may   48  ISUZU  D-MAX SC
5956  2010   may    0  ISUZU  D-MAX SC
5770  2010   nov    0  ISUZU  D-MAX SC
5962  2010   nov    0  ISUZU  D-MAX SC
5769  2010   oct   15  ISUZU  D-MAX SC
5961  2010   oct    0  ISUZU  D-MAX SC
5768  2010   sep   40  ISUZU  D-MAX SC
5960  2010   sep    0  ISUZU  D-MAX SC
5775  2011   apr   14  ISUZU  D-MAX SC
5967  2011   apr    0  ISUZU  D-MAX SC
5779  2011   aug   24  ISUZU  D-MAX SC
5971  2011   aug    0  ISUZU  D-MAX SC
5783  2011   dec    0  ISUZU  D-MAX SC
5975  2011   dec    0  ISUZU  D-MAX SC
5773  2011   feb   15  ISUZU  D-MAX SC
5965  2011   feb    0  ISUZU  D-MAX SC
5772  2011   jan   45  ISUZU  D-MAX SC
5964  2011   jan    0  ISUZU  D-MAX SC
5778  2011   jul    9  ISUZU  D-MAX SC
5970  2011   jul    0  ISUZU  D-MAX SC
5777  2011   jun   32  ISUZU  D-MAX SC
5969  2011   jun    0  ISUZU  D-MAX SC
5774  2011   mar   20  ISUZU  D-MAX SC
5966  2011   mar    0  ISUZU  D-MAX SC
5776  2011   may   31  ISUZU  D-MAX SC
5968  2011   may    0  ISUZU  D-MAX SC
5782  2011   nov    0  ISUZU  D-MAX SC
5974  2011   nov    0  ISUZU  D-MAX SC
5781  2011   oct   25  ISUZU  D-MAX SC
5973  2011   oct    0  ISUZU  D-MAX SC
5780  2011   sep   10  ISUZU  D-MAX SC
5972  2011   sep    0  ISUZU  D-MAX SC
5787  2012   apr   15  ISUZU  D-MAX SC
5979  2012   apr    0  ISUZU  D-MAX SC

In [13]:
df_isuzu.to_csv(
    "isuzu_ok_models.csv",
    index=False,
    encoding="utf-8-sig"
)

In [14]:

df_ok = final_df.copy()


df_lexus = df_ok[df_ok["brand"].str.upper() == "LEXUS"]

df_lexus = df_lexus[["year", "month", "sum", "brand", "model"]]


df_lexus = df_lexus.sort_values(["model", "year", "month"])

df_lexus.head(50)

      year month  sum  brand   model
3651  2010   apr   15  LEXUS  LX 570
3843  2010   apr    0  LEXUS  LX 570
4035  2010   apr    0  LEXUS  LX 570
3655  2010   aug   10  LEXUS  LX 570
3847  2010   aug    0  LEXUS  LX 570
4039  2010   aug    0  LEXUS  LX 570
3659  2010   dec    0  LEXUS  LX 570
3851  2010   dec    0  LEXUS  LX 570
4043  2010   dec    0  LEXUS  LX 570
3649  2010   feb   19  LEXUS  LX 570
3841  2010   feb    0  LEXUS  LX 570
4033  2010   feb    0  LEXUS  LX 570
3648  2010   jan    0  LEXUS  LX 570
3840  2010   jan    0  LEXUS  LX 570
4032  2010   jan    0  LEXUS  LX 570
3654  2010   jul   11  LEXUS  LX 570
3846  2010   jul    0  LEXUS  LX 570
4038  2010   jul    0  LEXUS  LX 570
3653  2010   jun    3  LEXUS  LX 570
3845  2010   jun    0  LEXUS  LX 570
4037  2010   jun    0  LEXUS  LX 570
3650  2010   mar   35  LEXUS  LX 570
3842  2010   mar    0  LEXUS  LX 570
4034  2010   mar    0  LEXUS  LX 570
3652  2010   may    9  LEXUS  LX 570
3844  2010   may    0  LEXUS  LX 570
4036  2010   may    0  LEXUS  LX 570
3658  2010   nov   10  LEXUS  LX 570
3850  2010   nov    0  LEXUS  LX 570
4042  2010   nov    0  LEXUS  LX 570
3657  2010   oct    5  LEXUS  LX 570
3849  2010   oct    0  LEXUS  LX 570
4041  2010   oct    0  LEXUS  LX 570
3656  2010   sep    6  LEXUS  LX 570
3848  2010   sep    0  LEXUS  LX 570
4040  2010   sep    0  LEXUS  LX 570
3663  2011   apr   13  LEXUS  LX 570
3855  2011   apr    0  LEXUS  LX 570
4047  2011   apr    0  LEXUS  LX 570
3667  2011   aug   25  LEXUS  LX 570
3859  2011   aug    0  LEXUS  LX 570
4051  2011   aug    0  LEXUS  LX 570
3671  2011   dec    6  LEXUS  LX 570
3863  2011   dec    0  LEXUS  LX 570
4055  2011   dec    0  LEXUS  LX 570
3661  2011   feb   10  LEXUS  LX 570
3853  2011   feb    0  LEXUS  LX 570
4045  2011   feb    0  LEXUS  LX 570
3660  2011   jan    0  LEXUS  LX 570
3852  2011   jan    0  LEXUS  LX 570

In [15]:
df_lexus.to_csv(
    "lexus_ok_models.csv",
    index=False,
    encoding="utf-8-sig"
)

In [16]:

df_ok = final_df.copy()


df_mitsubishi = df_ok[df_ok["brand"].str.upper() == "MITSUBISHI"]


df_mitsubishi = df_mitsubishi[["year", "month", "sum", "brand", "model"]]


df_mitsubishi = df_mitsubishi.sort_values(["model", "year", "month"])

df_mitsubishi.head(50)

       year month  sum       brand            model
35139  2010   apr    0  MITSUBISHI  L 300 D P/U FLD
35331  2010   apr    0  MITSUBISHI  L 300 D P/U FLD
35523  2010   apr    0  MITSUBISHI  L 300 D P/U FLD
35143  2010   aug    0  MITSUBISHI  L 300 D P/U FLD
35335  2010   aug    0  MITSUBISHI  L 300 D P/U FLD
35527  2010   aug    0  MITSUBISHI  L 300 D P/U FLD
35147  2010   dec    0  MITSUBISHI  L 300 D P/U FLD
35339  2010   dec    0  MITSUBISHI  L 300 D P/U FLD
35531  2010   dec    0  MITSUBISHI  L 300 D P/U FLD
35137  2010   feb    0  MITSUBISHI  L 300 D P/U FLD
35329  2010   feb    0  MITSUBISHI  L 300 D P/U FLD
35521  2010   feb    0  MITSUBISHI  L 300 D P/U FLD
35136  2010   jan    0  MITSUBISHI  L 300 D P/U FLD
35328  2010   jan    0  MITSUBISHI  L 300 D P/U FLD
35520  2010   jan    0  MITSUBISHI  L 300 D P/U FLD
35142  2010   jul    0  MITSUBISHI  L 300 D P/U FLD
35334  2010   jul    0  MITSUBISHI  L 300 D P/U FLD
35526  2010   jul    0  MITSUBISHI  L 300 D P/U FLD
35141  2010   jun    0  MITSUBISHI  L 300 D P/U FLD
35333  2010   jun    0  MITSUBISHI  L 300 D P/U FLD
35525  2010   jun    0  MITSUBISHI  L 300 D P/U FLD
35138  2010   mar    0  MITSUBISHI  L 300 D P/U FLD
35330  2010   mar    0  MITSUBISHI  L 300 D P/U FLD
35522  2010   mar    0  MITSUBISHI  L 300 D P/U FLD
35140  2010   may    0  MITSUBISHI  L 300 D P/U FLD
35332  2010   may    0  MITSUBISHI  L 300 D P/U FLD
35524  2010   may    0  MITSUBISHI  L 300 D P/U FLD
35146  2010   nov    0  MITSUBISHI  L 300 D P/U FLD
35338  2010   nov    0  MITSUBISHI  L 300 D P/U FLD
35530  2010   nov    0  MITSUBISHI  L 300 D P/U FLD
35145  2010   oct    0  MITSUBISHI  L 300 D P/U FLD
35337  2010   oct    0  MITSUBISHI  L 300 D P/U FLD
35529  2010   oct    0  MITSUBISHI  L 300 D P/U FLD
35144  2010   sep    0  MITSUBISHI  L 300 D P/U FLD
35336  2010   sep    0  MITSUBISHI  L 300 D P/U FLD
35528  2010   sep    0  MITSUBISHI  L 300 D P/U FLD
35151  2011   apr    0  MITSUBISHI  L 300 D P/U FLD
35343  2011   apr    0  MITSUBISHI  L 300 D P/U FLD
35535  2011   apr    0  MITSUBISHI  L 300 D P/U FLD
35155  2011   aug    0  MITSUBISHI  L 300 D P/U FLD
35347  2011   aug    0  MITSUBISHI  L 300 D P/U FLD
35539  2011   aug    0  MITSUBISHI  L 300 D P/U FLD
35159  2011   dec    0  MITSUBISHI  L 300 D P/U FLD
35351  2011   dec    0  MITSUBISHI  L 300 D P/U FLD
35543  2011   dec    0  MITSUBISHI  L 300 D P/U FLD
35149  2011   feb    0  MITSUBISHI  L 300 D P/U FLD
35341  2011   feb    0  MITSUBISHI  L 300 D P/U FLD
35533  2011   feb    0  MITSUBISHI  L 300 D P/U FLD
35148  2011   jan    0  MITSUBISHI  L 300 D P/U FLD
35340  2011   jan    0  MITSUBISHI  L 300 D P/U FLD

In [17]:
df_mitsubishi.to_csv(
    "mitsubishi_ok_models.csv",
    index=False,
    encoding="utf-8-sig"
)

In [18]:

df_ok = final_df.copy()


df_nissan = df_ok[df_ok["brand"].str.upper() == "NISSAN"]


df_nissan = df_nissan[["year", "month", "sum", "brand", "model"]]


df_nissan = df_nissan.sort_values(["model", "year", "month"])

df_nissan.head(50)

       year month  sum   brand          model
29571  2010   apr    0  NISSAN  Juke Revolt 2
29575  2010   aug    0  NISSAN  Juke Revolt 2
29579  2010   dec    0  NISSAN  Juke Revolt 2
29569  2010   feb    0  NISSAN  Juke Revolt 2
29568  2010   jan    0  NISSAN  Juke Revolt 2
29574  2010   jul    0  NISSAN  Juke Revolt 2
29573  2010   jun    0  NISSAN  Juke Revolt 2
29570  2010   mar    0  NISSAN  Juke Revolt 2
29572  2010   may    0  NISSAN  Juke Revolt 2
29578  2010   nov    0  NISSAN  Juke Revolt 2
29577  2010   oct    0  NISSAN  Juke Revolt 2
29576  2010   sep    0  NISSAN  Juke Revolt 2
29583  2011   apr    0  NISSAN  Juke Revolt 2
29587  2011   aug    0  NISSAN  Juke Revolt 2
29591  2011   dec    0  NISSAN  Juke Revolt 2
29581  2011   feb    0  NISSAN  Juke Revolt 2
29580  2011   jan    0  NISSAN  Juke Revolt 2
29586  2011   jul    0  NISSAN  Juke Revolt 2
29585  2011   jun    0  NISSAN  Juke Revolt 2
29582  2011   mar    0  NISSAN  Juke Revolt 2
29584  2011   may    0  NISSAN  Juke Revolt 2
29590  2011   nov    0  NISSAN  Juke Revolt 2
29589  2011   oct    0  NISSAN  Juke Revolt 2
29588  2011   sep    0  NISSAN  Juke Revolt 2
29595  2012   apr    0  NISSAN  Juke Revolt 2
29599  2012   aug    0  NISSAN  Juke Revolt 2
29603  2012   dec    0  NISSAN  Juke Revolt 2
29593  2012   feb    0  NISSAN  Juke Revolt 2
29592  2012   jan    0  NISSAN  Juke Revolt 2
29598  2012   jul    0  NISSAN  Juke Revolt 2
29597  2012   jun    0  NISSAN  Juke Revolt 2
29594  2012   mar    0  NISSAN  Juke Revolt 2
29596  2012   may    0  NISSAN  Juke Revolt 2
29602  2012   nov    0  NISSAN  Juke Revolt 2
29601  2012   oct    0  NISSAN  Juke Revolt 2
29600  2012   sep    0  NISSAN  Juke Revolt 2
29607  2013   apr    0  NISSAN  Juke Revolt 2
29611  2013   aug    0  NISSAN  Juke Revolt 2
29615  2013   dec    0  NISSAN  Juke Revolt 2
29605  2013   feb    0  NISSAN  Juke Revolt 2
29604  2013   jan    0  NISSAN  Juke Revolt 2
29610  2013   jul    0  NISSAN  Juke Revolt 2
29609  2013   jun    0  NISSAN  Juke Revolt 2
29606  2013   mar    0  NISSAN  Juke Revolt 2
29608  2013   may    0  NISSAN  Juke Revolt 2
29614  2013   nov    0  NISSAN  Juke Revolt 2
29613  2013   oct    0  NISSAN  Juke Revolt 2
29612  2013   sep    0  NISSAN  Juke Revolt 2
29619  2014   apr    0  NISSAN  Juke Revolt 2
29623  2014   aug    0  NISSAN  Juke Revolt 2

In [19]:
df_nissan.to_csv(
    "nissan_ok_models.csv",
    index=False,
    encoding="utf-8-sig"
)

In [20]:

df_ok = final_df.copy()


df_suzuki = df_ok[df_ok["brand"].str.upper() == "SUZUKI"]


df_suzuki = df_suzuki[["year", "month", "sum", "brand", "model"]]


df_suzuki = df_suzuki.sort_values(["model", "year", "month"])

df_suzuki.head(50)

      year month  sum   brand   model
1923  2010   apr   86  SUZUKI  APV GE
2115  2010   apr    0  SUZUKI  APV GE
1927  2010   aug   72  SUZUKI  APV GE
2119  2010   aug    0  SUZUKI  APV GE
1931  2010   dec   83  SUZUKI  APV GE
2123  2010   dec    0  SUZUKI  APV GE
1921  2010   feb   89  SUZUKI  APV GE
2113  2010   feb    0  SUZUKI  APV GE
1920  2010   jan  125  SUZUKI  APV GE
2112  2010   jan    0  SUZUKI  APV GE
1926  2010   jul  186  SUZUKI  APV GE
2118  2010   jul    0  SUZUKI  APV GE
1925  2010   jun  221  SUZUKI  APV GE
2117  2010   jun    0  SUZUKI  APV GE
1922  2010   mar  120  SUZUKI  APV GE
2114  2010   mar    0  SUZUKI  APV GE
1924  2010   may   82  SUZUKI  APV GE
2116  2010   may    0  SUZUKI  APV GE
1930  2010   nov  283  SUZUKI  APV GE
2122  2010   nov    0  SUZUKI  APV GE
1929  2010   oct  328  SUZUKI  APV GE
2121  2010   oct    0  SUZUKI  APV GE
1928  2010   sep   88  SUZUKI  APV GE
2120  2010   sep    0  SUZUKI  APV GE
1935  2011   apr  176  SUZUKI  APV GE
2127  2011   apr    0  SUZUKI  APV GE
1939  2011   aug  240  SUZUKI  APV GE
2131  2011   aug    0  SUZUKI  APV GE
1943  2011   dec  117  SUZUKI  APV GE
2135  2011   dec    0  SUZUKI  APV GE
1933  2011   feb  161  SUZUKI  APV GE
2125  2011   feb    0  SUZUKI  APV GE
1932  2011   jan  322  SUZUKI  APV GE
2124  2011   jan    0  SUZUKI  APV GE
1938  2011   jul  220  SUZUKI  APV GE
2130  2011   jul    0  SUZUKI  APV GE
1937  2011   jun  204  SUZUKI  APV GE
2129  2011   jun    0  SUZUKI  APV GE
1934  2011   mar  207  SUZUKI  APV GE
2126  2011   mar    0  SUZUKI  APV GE
1936  2011   may  251  SUZUKI  APV GE
2128  2011   may    0  SUZUKI  APV GE
1942  2011   nov  249  SUZUKI  APV GE
2134  2011   nov    0  SUZUKI  APV GE
1941  2011   oct  335  SUZUKI  APV GE
2133  2011   oct    0  SUZUKI  APV GE
1940  2011   sep  397  SUZUKI  APV GE
2132  2011   sep    0  SUZUKI  APV GE
1947  2012   apr    0  SUZUKI  APV GE
2139  2012   apr  190  SUZUKI  APV GE

In [21]:
df_suzuki.to_csv(
    "suzuki_ok_models.csv",
    index=False,
    encoding="utf-8-sig"
)

In [22]:

df_ok = final_df.copy()


df_tata = df_ok[df_ok["brand"].str.upper() == "TATA"]


df_tata = df_tata[["year", "month", "sum", "brand", "model"]]


df_tata = df_tata.sort_values(["model", "year", "month"])

df_tata.head(50)

       year month  sum brand     model
17283  2010   apr    0  TATA  ACE EX 2
17475  2010   apr    0  TATA  ACE EX 2
17287  2010   aug    0  TATA  ACE EX 2
17479  2010   aug    0  TATA  ACE EX 2
17291  2010   dec    0  TATA  ACE EX 2
17483  2010   dec    0  TATA  ACE EX 2
17281  2010   feb    0  TATA  ACE EX 2
17473  2010   feb    0  TATA  ACE EX 2
17280  2010   jan    0  TATA  ACE EX 2
17472  2010   jan    0  TATA  ACE EX 2
17286  2010   jul    0  TATA  ACE EX 2
17478  2010   jul    0  TATA  ACE EX 2
17285  2010   jun    0  TATA  ACE EX 2
17477  2010   jun    0  TATA  ACE EX 2
17282  2010   mar    0  TATA  ACE EX 2
17474  2010   mar    0  TATA  ACE EX 2
17284  2010   may    0  TATA  ACE EX 2
17476  2010   may    0  TATA  ACE EX 2
17290  2010   nov    0  TATA  ACE EX 2
17482  2010   nov    0  TATA  ACE EX 2
17289  2010   oct    0  TATA  ACE EX 2
17481  2010   oct    0  TATA  ACE EX 2
17288  2010   sep    0  TATA  ACE EX 2
17480  2010   sep    0  TATA  ACE EX 2
17295  2011   apr    0  TATA  ACE EX 2
17487  2011   apr    0  TATA  ACE EX 2
17299  2011   aug    0  TATA  ACE EX 2
17491  2011   aug    0  TATA  ACE EX 2
17303  2011   dec    0  TATA  ACE EX 2
17495  2011   dec    0  TATA  ACE EX 2
17293  2011   feb    0  TATA  ACE EX 2
17485  2011   feb    0  TATA  ACE EX 2
17292  2011   jan    0  TATA  ACE EX 2
17484  2011   jan    0  TATA  ACE EX 2
17298  2011   jul    0  TATA  ACE EX 2
17490  2011   jul    0  TATA  ACE EX 2
17297  2011   jun    0  TATA  ACE EX 2
17489  2011   jun    0  TATA  ACE EX 2
17294  2011   mar    0  TATA  ACE EX 2
17486  2011   mar    0  TATA  ACE EX 2
17296  2011   may    0  TATA  ACE EX 2
17488  2011   may    0  TATA  ACE EX 2
17302  2011   nov    0  TATA  ACE EX 2
17494  2011   nov    0  TATA  ACE EX 2
17301  2011   oct    0  TATA  ACE EX 2
17493  2011   oct    0  TATA  ACE EX 2
17300  2011   sep    0  TATA  ACE EX 2
17492  2011   sep    0  TATA  ACE EX 2
17307  2012   apr    0  TATA  ACE EX 2
17499  2012   apr    0  TATA  ACE EX 2

In [23]:
df_tata.to_csv(
    "tata_ok_models.csv",
    index=False,
    encoding="utf-8-sig"
)

In [24]:

df_ok = final_df.copy()

df_toyota = df_ok[df_ok["brand"].str.upper() == "TOYOTA"]

df_toyota = df_toyota[["year", "month", "sum", "brand", "model"]]


df_toyota = df_toyota.sort_values(["model", "year", "month"])

df_toyota.head(50)

       year month  sum   brand  model
9987   2010   apr    0  TOYOTA  86 AT
9991   2010   aug    0  TOYOTA  86 AT
9995   2010   dec    0  TOYOTA  86 AT
9985   2010   feb    0  TOYOTA  86 AT
9984   2010   jan    0  TOYOTA  86 AT
9990   2010   jul    0  TOYOTA  86 AT
9989   2010   jun    0  TOYOTA  86 AT
9986   2010   mar    0  TOYOTA  86 AT
9988   2010   may    0  TOYOTA  86 AT
9994   2010   nov    0  TOYOTA  86 AT
9993   2010   oct    0  TOYOTA  86 AT
9992   2010   sep    0  TOYOTA  86 AT
9999   2011   apr    0  TOYOTA  86 AT
10003  2011   aug    0  TOYOTA  86 AT
10007  2011   dec    0  TOYOTA  86 AT
9997   2011   feb    0  TOYOTA  86 AT
9996   2011   jan    0  TOYOTA  86 AT
10002  2011   jul    0  TOYOTA  86 AT
10001  2011   jun    0  TOYOTA  86 AT
9998   2011   mar    0  TOYOTA  86 AT
10000  2011   may    0  TOYOTA  86 AT
10006  2011   nov    0  TOYOTA  86 AT
10005  2011   oct    0  TOYOTA  86 AT
10004  2011   sep    0  TOYOTA  86 AT
10011  2012   apr    0  TOYOTA  86 AT
10015  2012   aug    4  TOYOTA  86 AT
10019  2012   dec   14  TOYOTA  86 AT
10009  2012   feb    0  TOYOTA  86 AT
10008  2012   jan    0  TOYOTA  86 AT
10014  2012   jul    3  TOYOTA  86 AT
10013  2012   jun   35  TOYOTA  86 AT
10010  2012   mar    0  TOYOTA  86 AT
10012  2012   may    0  TOYOTA  86 AT
10018  2012   nov    2  TOYOTA  86 AT
10017  2012   oct    4  TOYOTA  86 AT
10016  2012   sep    2  TOYOTA  86 AT
10023  2013   apr    2  TOYOTA  86 AT
10027  2013   aug    2  TOYOTA  86 AT
10031  2013   dec    0  TOYOTA  86 AT
10021  2013   feb    2  TOYOTA  86 AT
10020  2013   jan   17  TOYOTA  86 AT
10026  2013   jul    1  TOYOTA  86 AT
10025  2013   jun    1  TOYOTA  86 AT
10022  2013   mar    0  TOYOTA  86 AT
10024  2013   may    2  TOYOTA  86 AT
10030  2013   nov    4  TOYOTA  86 AT
10029  2013   oct    0  TOYOTA  86 AT
10028  2013   sep    3  TOYOTA  86 AT
10035  2014   apr    2  TOYOTA  86 AT
10039  2014   aug    0  TOYOTA  86 AT

In [25]:
df_toyota.to_csv(
    "toyota_ok_models.csv",
    index=False,
    encoding="utf-8-sig"
)

In [26]:

df_ok = final_df.copy()


df_vw = df_ok[df_ok["brand"].str.upper() == "VOLKSWAGEN"]

df_vw = df_vw[["year", "month", "sum", "brand", "model"]]


df_vw = df_vw.sort_values(["model", "year", "month"])

df_vw.head(50)

       year month  sum       brand               model
20931  2010   apr    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20935  2010   aug    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20939  2010   dec    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20929  2010   feb    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20928  2010   jan    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20934  2010   jul    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20933  2010   jun    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20930  2010   mar    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20932  2010   may    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20938  2010   nov    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20937  2010   oct    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20936  2010   sep    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20943  2011   apr    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20947  2011   aug    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20951  2011   dec    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20941  2011   feb    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20940  2011   jan    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20946  2011   jul    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20945  2011   jun    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20942  2011   mar    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20944  2011   may    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20950  2011   nov    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20949  2011   oct    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20948  2011   sep    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20955  2012   apr    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20959  2012   aug    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20963  2012   dec    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20953  2012   feb    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20952  2012   jan    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20958  2012   jul    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20957  2012   jun    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20954  2012   mar    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20956  2012   may    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20962  2012   nov    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20961  2012   oct    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20960  2012   sep    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20967  2013   apr    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20971  2013   aug    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20975  2013   dec    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20965  2013   feb    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20964  2013   jan    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20970  2013   jul    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20969  2013   jun    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20966  2013   mar    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20968  2013   may    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20974  2013   nov    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20973  2013   oct    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20972  2013   sep    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20979  2014   apr    0  VOLKSWAGEN  Polo 1.2 GT TSI AT
20983  2014   aug    0  VOLKSWAGEN  Polo 1.2 GT TSI AT

In [27]:
df_vw.to_csv(
    "volkswagen_ok_models.csv",
    index=False,
    encoding="utf-8-sig"
)

In [28]:

df_ok = final_df.copy()

df_audi = df_ok[df_ok["brand"].str.upper() == "AUDI"]


df_audi = df_audi[["year", "month", "sum", "brand", "model"]]


df_audi = df_audi.sort_values(["model", "year", "month"])

df_audi.head(50)

       year month  sum brand             model
16323  2010   apr    0  AUDI  Q 3 1.4 TFSI A/T
16515  2010   apr    0  AUDI  Q 3 1.4 TFSI A/T
16327  2010   aug    0  AUDI  Q 3 1.4 TFSI A/T
16519  2010   aug    0  AUDI  Q 3 1.4 TFSI A/T
16331  2010   dec    0  AUDI  Q 3 1.4 TFSI A/T
16523  2010   dec    0  AUDI  Q 3 1.4 TFSI A/T
16321  2010   feb    0  AUDI  Q 3 1.4 TFSI A/T
16513  2010   feb    0  AUDI  Q 3 1.4 TFSI A/T
16320  2010   jan    0  AUDI  Q 3 1.4 TFSI A/T
16512  2010   jan    0  AUDI  Q 3 1.4 TFSI A/T
16326  2010   jul    0  AUDI  Q 3 1.4 TFSI A/T
16518  2010   jul    0  AUDI  Q 3 1.4 TFSI A/T
16325  2010   jun    0  AUDI  Q 3 1.4 TFSI A/T
16517  2010   jun    0  AUDI  Q 3 1.4 TFSI A/T
16322  2010   mar    0  AUDI  Q 3 1.4 TFSI A/T
16514  2010   mar    0  AUDI  Q 3 1.4 TFSI A/T
16324  2010   may    0  AUDI  Q 3 1.4 TFSI A/T
16516  2010   may    0  AUDI  Q 3 1.4 TFSI A/T
16330  2010   nov    0  AUDI  Q 3 1.4 TFSI A/T
16522  2010   nov    0  AUDI  Q 3 1.4 TFSI A/T
16329  2010   oct    0  AUDI  Q 3 1.4 TFSI A/T
16521  2010   oct    0  AUDI  Q 3 1.4 TFSI A/T
16328  2010   sep    0  AUDI  Q 3 1.4 TFSI A/T
16520  2010   sep    0  AUDI  Q 3 1.4 TFSI A/T
16335  2011   apr    0  AUDI  Q 3 1.4 TFSI A/T
16527  2011   apr    0  AUDI  Q 3 1.4 TFSI A/T
16339  2011   aug    0  AUDI  Q 3 1.4 TFSI A/T
16531  2011   aug    0  AUDI  Q 3 1.4 TFSI A/T
16343  2011   dec    0  AUDI  Q 3 1.4 TFSI A/T
16535  2011   dec    0  AUDI  Q 3 1.4 TFSI A/T
16333  2011   feb    0  AUDI  Q 3 1.4 TFSI A/T
16525  2011   feb    0  AUDI  Q 3 1.4 TFSI A/T
16332  2011   jan    0  AUDI  Q 3 1.4 TFSI A/T
16524  2011   jan    0  AUDI  Q 3 1.4 TFSI A/T
16338  2011   jul    0  AUDI  Q 3 1.4 TFSI A/T
16530  2011   jul    0  AUDI  Q 3 1.4 TFSI A/T
16337  2011   jun    0  AUDI  Q 3 1.4 TFSI A/T
16529  2011   jun    0  AUDI  Q 3 1.4 TFSI A/T
16334  2011   mar    0  AUDI  Q 3 1.4 TFSI A/T
16526  2011   mar    0  AUDI  Q 3 1.4 TFSI A/T
16336  2011   may    0  AUDI  Q 3 1.4 TFSI A/T
16528  2011   may    0  AUDI  Q 3 1.4 TFSI A/T
16342  2011   nov    0  AUDI  Q 3 1.4 TFSI A/T
16534  2011   nov    0  AUDI  Q 3 1.4 TFSI A/T
16341  2011   oct    0  AUDI  Q 3 1.4 TFSI A/T
16533  2011   oct    0  AUDI  Q 3 1.4 TFSI A/T
16340  2011   sep    0  AUDI  Q 3 1.4 TFSI A/T
16532  2011   sep    0  AUDI  Q 3 1.4 TFSI A/T
16347  2012   apr    0  AUDI  Q 3 1.4 TFSI A/T
16539  2012   apr    0  AUDI  Q 3 1.4 TFSI A/T

In [29]:
df_audi.to_csv(
    "audi_ok_models.csv",
    index=False,
    encoding="utf-8-sig"
)

In [30]:
import pandas as pd

df = pd.read_excel("dataset_final_new_new.xlsx")
df.columns = df.columns.astype(str).str.strip().str.lower()


df["year"] = pd.to_numeric(df["year"], errors="coerce")
df["sum"]  = pd.to_numeric(df["sum"], errors="coerce")


df_p = df[df["year"].between(2016, 2020)].copy()


yearly = (
    df_p.groupby(["brand", "model", "year"], as_index=False)["sum"]
    .sum()
)


ok_models = (
    yearly[yearly["sum"] > 0]
    .groupby(["brand", "model"])["year"]
    .nunique()
    .reset_index(name="n_years")
)

ok_models = ok_models[ok_models["n_years"] == 5][["brand", "model"]]


final_df = df.merge(ok_models, on=["brand", "model"], how="inner")
final_df = final_df[final_df["year"].between(2016, 2020)]

print("Моделей прошло фильтр (2016–2020):", ok_models.shape[0])
final_df.head()

Моделей прошло фильтр (2016–2020): 162

    year month  sum  brand                     model fuel    cc
72  2016   jan   28  HONDA  All New City i VTEC E AT    g  1497
73  2016   feb   73  HONDA  All New City i VTEC E AT    g  1497
74  2016   mar  102  HONDA  All New City i VTEC E AT    g  1497
75  2016   apr    7  HONDA  All New City i VTEC E AT    g  1497
76  2016   may   97  HONDA  All New City i VTEC E AT    g  1497

In [31]:

final_df = final_df.sort_values(["brand", "model", "year", "month"])


final_df.to_csv(
    "filtered_models_2016_2020.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Файл сохранён как filtered_models_2016_2020.csv")

Файл сохранён как filtered_models_2016_2020.csv